/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// AtlasMetadata
    /// </summary>
    [DataContract(Name = "AtlasMetadata")]
    public partial class AtlasMetadata
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AtlasMetadata" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AtlasMetadata() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AtlasMetadata" /> class.
        /// </summary>
        /// <param name="identifier">identifier (required).</param>
        /// <param name="slotId">slotId (required).</param>
        /// <param name="atlasIndex">atlasIndex (required).</param>
        /// <param name="position">position (required).</param>
        /// <param name="x">x (required).</param>
        /// <param name="y">y (required).</param>
        /// <param name="width">width (required).</param>
        /// <param name="height">height (required).</param>
        public AtlasMetadata(string identifier = default(string), int slotId = default(int), int atlasIndex = default(int), Rectangle position = default(Rectangle), int x = default(int), int y = default(int), int width = default(int), int height = default(int))
        {
            // to ensure "identifier" is required (not null)
            if (identifier == null)
            {
                throw new ArgumentNullException("identifier is a required property for AtlasMetadata and cannot be null");
            }
            this.Identifier = identifier;
            this.SlotId = slotId;
            this.AtlasIndex = atlasIndex;
            // to ensure "position" is required (not null)
            if (position == null)
            {
                throw new ArgumentNullException("position is a required property for AtlasMetadata and cannot be null");
            }
            this.Position = position;
            this.X = x;
            this.Y = y;
            this.Width = width;
            this.Height = height;
        }

        /// <summary>
        /// Gets or Sets Identifier
        /// </summary>
        [DataMember(Name = "identifier", IsRequired = true, EmitDefaultValue = true)]
        public string Identifier { get; set; }

        /// <summary>
        /// Gets or Sets SlotId
        /// </summary>
        [DataMember(Name = "slotId", IsRequired = true, EmitDefaultValue = true)]
        public int SlotId { get; set; }

        /// <summary>
        /// Gets or Sets AtlasIndex
        /// </summary>
        [DataMember(Name = "atlasIndex", IsRequired = true, EmitDefaultValue = true)]
        public int AtlasIndex { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", IsRequired = true, EmitDefaultValue = true)]
        public Rectangle Position { get; set; }

        /// <summary>
        /// Gets or Sets X
        /// </summary>
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public int X { get; set; }

        /// <summary>
        /// Gets or Sets Y
        /// </summary>
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public int Y { get; set; }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", IsRequired = true, EmitDefaultValue = true)]
        public int Width { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = true)]
        public int Height { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AtlasMetadata {\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  SlotId: ").Append(SlotId).Append("\n");
            sb.Append("  AtlasIndex: ").Append(AtlasIndex).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
