/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// AutoAssignRoles
    /// </summary>
    [DataContract(Name = "AutoAssignRoles")]
    public partial class AutoAssignRoles
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutoAssignRoles" /> class.
        /// </summary>
        /// <param name="ageVerifiedRoleId">ageVerifiedRoleId.</param>
        /// <param name="ageVerifiedPlus18RoleId">ageVerifiedPlus18RoleId.</param>
        /// <param name="linkedRoleId">linkedRoleId.</param>
        public AutoAssignRoles(string ageVerifiedRoleId = default(string), string ageVerifiedPlus18RoleId = default(string), string linkedRoleId = default(string))
        {
            this.AgeVerifiedRoleId = ageVerifiedRoleId;
            this.AgeVerifiedPlus18RoleId = ageVerifiedPlus18RoleId;
            this.LinkedRoleId = linkedRoleId;
        }

        /// <summary>
        /// Gets or Sets AgeVerifiedRoleId
        /// </summary>
        [DataMember(Name = "ageVerifiedRoleId", EmitDefaultValue = true)]
        public string AgeVerifiedRoleId { get; set; }

        /// <summary>
        /// Gets or Sets AgeVerifiedPlus18RoleId
        /// </summary>
        [DataMember(Name = "ageVerifiedPlus18RoleId", EmitDefaultValue = true)]
        public string AgeVerifiedPlus18RoleId { get; set; }

        /// <summary>
        /// Gets or Sets LinkedRoleId
        /// </summary>
        [DataMember(Name = "linkedRoleId", EmitDefaultValue = true)]
        public string LinkedRoleId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutoAssignRoles {\n");
            sb.Append("  AgeVerifiedRoleId: ").Append(AgeVerifiedRoleId).Append("\n");
            sb.Append("  AgeVerifiedPlus18RoleId: ").Append(AgeVerifiedPlus18RoleId).Append("\n");
            sb.Append("  LinkedRoleId: ").Append(LinkedRoleId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
