/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// GetGuestRolesResponse
    /// </summary>
    [DataContract(Name = "GetGuestRolesResponse")]
    public partial class GetGuestRolesResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetGuestRolesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetGuestRolesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetGuestRolesResponse" /> class.
        /// </summary>
        /// <param name="guestRoles">guestRoles (required).</param>
        public GetGuestRolesResponse(List<GuestRole> guestRoles = default(List<GuestRole>))
        {
            // to ensure "guestRoles" is required (not null)
            if (guestRoles == null)
            {
                throw new ArgumentNullException("guestRoles is a required property for GetGuestRolesResponse and cannot be null");
            }
            this.GuestRoles = guestRoles;
        }

        /// <summary>
        /// Gets or Sets GuestRoles
        /// </summary>
        [DataMember(Name = "guestRoles", IsRequired = true, EmitDefaultValue = true)]
        public List<GuestRole> GuestRoles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetGuestRolesResponse {\n");
            sb.Append("  GuestRoles: ").Append(GuestRoles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
