/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// GetServerSlotsResponse
    /// </summary>
    [DataContract(Name = "GetServerSlotsResponse")]
    public partial class GetServerSlotsResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetServerSlotsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetServerSlotsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetServerSlotsResponse" /> class.
        /// </summary>
        /// <param name="imageSlots">imageSlots (required).</param>
        public GetServerSlotsResponse(List<ImageSlotDto> imageSlots = default(List<ImageSlotDto>))
        {
            // to ensure "imageSlots" is required (not null)
            if (imageSlots == null)
            {
                throw new ArgumentNullException("imageSlots is a required property for GetServerSlotsResponse and cannot be null");
            }
            this.ImageSlots = imageSlots;
        }

        /// <summary>
        /// Gets or Sets ImageSlots
        /// </summary>
        [DataMember(Name = "imageSlots", IsRequired = true, EmitDefaultValue = true)]
        public List<ImageSlotDto> ImageSlots { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetServerSlotsResponse {\n");
            sb.Append("  ImageSlots: ").Append(ImageSlots).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
