/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// Defines LinkStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LinkStatus
    {
        /// <summary>
        /// Enum CodeFound for value: CodeFound
        /// </summary>
        [EnumMember(Value = "CodeFound")]
        CodeFound = 1,

        /// <summary>
        /// Enum CodeNotFound for value: CodeNotFound
        /// </summary>
        [EnumMember(Value = "CodeNotFound")]
        CodeNotFound = 2
    }

}
