/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// LinkData
    /// </summary>
    [DataContract(Name = "LinkData")]
    public partial class LinkData
    {

        /// <summary>
        /// Gets or Sets AgeVerification
        /// </summary>
        [DataMember(Name = "ageVerification", EmitDefaultValue = false)]
        public AgeVerification? AgeVerification { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkData" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="vrchatName">vrchatName.</param>
        /// <param name="isVerified">isVerified.</param>
        /// <param name="ageVerification">ageVerification.</param>
        public LinkData(string id = default(string), string vrchatName = default(string), bool? isVerified = default(bool?), AgeVerification? ageVerification = default(AgeVerification?))
        {
            this.Id = id;
            this.VrchatName = vrchatName;
            this.IsVerified = isVerified;
            this.AgeVerification = ageVerification;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets VrchatName
        /// </summary>
        [DataMember(Name = "vrchatName", EmitDefaultValue = true)]
        public string VrchatName { get; set; }

        /// <summary>
        /// Gets or Sets IsVerified
        /// </summary>
        [DataMember(Name = "isVerified", EmitDefaultValue = true)]
        public bool? IsVerified { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkData {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  VrchatName: ").Append(VrchatName).Append("\n");
            sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
            sb.Append("  AgeVerification: ").Append(AgeVerification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
