/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// LinkingResponse
    /// </summary>
    [DataContract(Name = "LinkingResponse")]
    public partial class LinkingResponse
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public Status Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkingResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkingResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkingResponse" /> class.
        /// </summary>
        /// <param name="verificationCode">verificationCode (required).</param>
        /// <param name="status">status (required).</param>
        public LinkingResponse(string verificationCode = default(string), Status status = default(Status))
        {
            // to ensure "verificationCode" is required (not null)
            if (verificationCode == null)
            {
                throw new ArgumentNullException("verificationCode is a required property for LinkingResponse and cannot be null");
            }
            this.VerificationCode = verificationCode;
            this.Status = status;
        }

        /// <summary>
        /// Gets or Sets VerificationCode
        /// </summary>
        [DataMember(Name = "verificationCode", IsRequired = true, EmitDefaultValue = true)]
        public string VerificationCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkingResponse {\n");
            sb.Append("  VerificationCode: ").Append(VerificationCode).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
