/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// Defines MemberStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MemberStatus
    {
        /// <summary>
        /// Enum Member for value: Member
        /// </summary>
        [EnumMember(Value = "Member")]
        Member = 1,

        /// <summary>
        /// Enum Invited for value: Invited
        /// </summary>
        [EnumMember(Value = "Invited")]
        Invited = 2,

        /// <summary>
        /// Enum Requested for value: Requested
        /// </summary>
        [EnumMember(Value = "Requested")]
        Requested = 3,

        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 4,

        /// <summary>
        /// Enum MinimumMemberCount for value: MinimumMemberCount
        /// </summary>
        [EnumMember(Value = "MinimumMemberCount")]
        MinimumMemberCount = 5
    }

}
