/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// SyncPostersRequest
    /// </summary>
    [DataContract(Name = "SyncPostersRequest")]
    public partial class SyncPostersRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncPostersRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SyncPostersRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncPostersRequest" /> class.
        /// </summary>
        /// <param name="posters">posters (required).</param>
        public SyncPostersRequest(List<UnityPosterData> posters = default(List<UnityPosterData>))
        {
            // to ensure "posters" is required (not null)
            if (posters == null)
            {
                throw new ArgumentNullException("posters is a required property for SyncPostersRequest and cannot be null");
            }
            this.Posters = posters;
        }

        /// <summary>
        /// Gets or Sets Posters
        /// </summary>
        [DataMember(Name = "posters", IsRequired = true, EmitDefaultValue = true)]
        public List<UnityPosterData> Posters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SyncPostersRequest {\n");
            sb.Append("  Posters: ").Append(Posters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
