/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// Defines TokenAuthStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TokenAuthStatus
    {
        /// <summary>
        /// Enum Ok for value: Ok
        /// </summary>
        [EnumMember(Value = "Ok")]
        Ok = 1,

        /// <summary>
        /// Enum Unauthorized for value: Unauthorized
        /// </summary>
        [EnumMember(Value = "Unauthorized")]
        Unauthorized = 2,

        /// <summary>
        /// Enum TokenExpired for value: TokenExpired
        /// </summary>
        [EnumMember(Value = "TokenExpired")]
        TokenExpired = 3,

        /// <summary>
        /// Enum TokenNotFound for value: TokenNotFound
        /// </summary>
        [EnumMember(Value = "TokenNotFound")]
        TokenNotFound = 4,

        /// <summary>
        /// Enum TokenNotAuthorizedYet for value: TokenNotAuthorizedYet
        /// </summary>
        [EnumMember(Value = "TokenNotAuthorizedYet")]
        TokenNotAuthorizedYet = 5,

        /// <summary>
        /// Enum Error for value: Error
        /// </summary>
        [EnumMember(Value = "Error")]
        Error = 6
    }

}
