/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// UnityPosterData
    /// </summary>
    [DataContract(Name = "UnityPosterData")]
    public partial class UnityPosterData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnityPosterData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UnityPosterData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UnityPosterData" /> class.
        /// </summary>
        /// <param name="slotId">slotId (required).</param>
        /// <param name="slotName">slotName.</param>
        public UnityPosterData(int slotId = default(int), string slotName = default(string))
        {
            this.SlotId = slotId;
            this.SlotName = slotName;
        }

        /// <summary>
        /// Gets or Sets SlotId
        /// </summary>
        [DataMember(Name = "slotId", IsRequired = true, EmitDefaultValue = true)]
        public int SlotId { get; set; }

        /// <summary>
        /// Gets or Sets SlotName
        /// </summary>
        [DataMember(Name = "slotName", EmitDefaultValue = true)]
        public string SlotName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnityPosterData {\n");
            sb.Append("  SlotId: ").Append(SlotId).Append("\n");
            sb.Append("  SlotName: ").Append(SlotName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
