/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// UpdateGuildRequest
    /// </summary>
    [DataContract(Name = "UpdateGuildRequest")]
    public partial class UpdateGuildRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGuildRequest" /> class.
        /// </summary>
        /// <param name="grpEnabled">grpEnabled.</param>
        /// <param name="encRoleList">encRoleList.</param>
        /// <param name="alwaysEncRoles">alwaysEncRoles.</param>
        /// <param name="autoAssignRoles">autoAssignRoles.</param>
        public UpdateGuildRequest(bool? grpEnabled = default(bool?), List<string> encRoleList = default(List<string>), List<string> alwaysEncRoles = default(List<string>), AutoAssignRoles autoAssignRoles = default(AutoAssignRoles))
        {
            this.GrpEnabled = grpEnabled;
            this.EncRoleList = encRoleList;
            this.AlwaysEncRoles = alwaysEncRoles;
            this.AutoAssignRoles = autoAssignRoles;
        }

        /// <summary>
        /// Gets or Sets GrpEnabled
        /// </summary>
        [DataMember(Name = "grpEnabled", EmitDefaultValue = true)]
        public bool? GrpEnabled { get; set; }

        /// <summary>
        /// Gets or Sets EncRoleList
        /// </summary>
        [DataMember(Name = "encRoleList", EmitDefaultValue = true)]
        public List<string> EncRoleList { get; set; }

        /// <summary>
        /// Gets or Sets AlwaysEncRoles
        /// </summary>
        [DataMember(Name = "alwaysEncRoles", EmitDefaultValue = true)]
        public List<string> AlwaysEncRoles { get; set; }

        /// <summary>
        /// Gets or Sets AutoAssignRoles
        /// </summary>
        [DataMember(Name = "autoAssignRoles", EmitDefaultValue = false)]
        public AutoAssignRoles AutoAssignRoles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateGuildRequest {\n");
            sb.Append("  GrpEnabled: ").Append(GrpEnabled).Append("\n");
            sb.Append("  EncRoleList: ").Append(EncRoleList).Append("\n");
            sb.Append("  AlwaysEncRoles: ").Append(AlwaysEncRoles).Append("\n");
            sb.Append("  AutoAssignRoles: ").Append(AutoAssignRoles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
