/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// SearchDetailsMember
    /// </summary>
    [DataContract(Name = "SearchDetailsMember")]
    public partial class SearchDetailsMember
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchDetailsMember" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchDetailsMember() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchDetailsMember" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="discordRoles">discordRoles (required).</param>
        public SearchDetailsMember(string id = default(string), List<string> discordRoles = default(List<string>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for SearchDetailsMember and cannot be null");
            }
            this.Id = id;
            // to ensure "discordRoles" is required (not null)
            if (discordRoles == null)
            {
                throw new ArgumentNullException("discordRoles is a required property for SearchDetailsMember and cannot be null");
            }
            this.DiscordRoles = discordRoles;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets DiscordRoles
        /// </summary>
        [DataMember(Name = "discordRoles", IsRequired = true, EmitDefaultValue = true)]
        public List<string> DiscordRoles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchDetailsMember {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DiscordRoles: ").Append(DiscordRoles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
