/*
 * VRCLinking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = VRCLinkingAPI.Client.OpenAPIDateConverter;

namespace VRCLinkingAPI.Model
{
    /// <summary>
    /// Defines SortType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SortType
    {
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 1,

        /// <summary>
        /// Enum Username for value: Username
        /// </summary>
        [EnumMember(Value = "Username")]
        Username = 2,

        /// <summary>
        /// Enum Id for value: Id
        /// </summary>
        [EnumMember(Value = "Id")]
        Id = 3,

        /// <summary>
        /// Enum DiscordRoles for value: DiscordRoles
        /// </summary>
        [EnumMember(Value = "DiscordRoles")]
        DiscordRoles = 4,

        /// <summary>
        /// Enum VrcId for value: VrcId
        /// </summary>
        [EnumMember(Value = "VrcId")]
        VrcId = 5,

        /// <summary>
        /// Enum VrcName for value: VrcName
        /// </summary>
        [EnumMember(Value = "VrcName")]
        VrcName = 6,

        /// <summary>
        /// Enum LinkLastChanged for value: LinkLastChanged
        /// </summary>
        [EnumMember(Value = "LinkLastChanged")]
        LinkLastChanged = 7,

        /// <summary>
        /// Enum LinkCount for value: LinkCount
        /// </summary>
        [EnumMember(Value = "LinkCount")]
        LinkCount = 8
    }

}
